---
title: '⚠️ Raspberry Pi カメラモジュール - オペレーティングシステムに関する注意'
hero_image: images/banner.png
description: Raspberry Pi OS での Picamera Python モジュールの使用方法
version: 4
listed: false
copyedit: false
last_tested: "2021-11-03"
steps:
  - 
    title: はじめに
