---
title: '⚠️ Módulo de cámara Raspberry Pi - Aviso del sistema operativo'
hero_image: images/banner.png
description: Cómo usar el módulo Picamera de Python con Raspberry Pi OS
version: 4
listed: false
copyedit: false
last_tested: "2021-11-03"
steps:
  - 
    title: Introducción
