---
title: '⚠️ Raspberry Pi Camera Module – Hinweis zum Betriebssystem'
hero_image: images/banner.png
description: So verwendest du das Picamera-Python-Modul mit dem Raspberry Pi OS
version: 4
listed: false
copyedit: false
last_tested: "2021-11-03"
steps:
  - 
    title: Einleitung
